# Generated by Django 5.2.10 on 2026-02-24 13:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('device_id', models.IntegerField(db_index=True, unique=True)),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=64)),
                ('private_key_path', models.CharField(blank=True, max_length=512)),
                ('public_key_path', models.CharField(blank=True, max_length=512)),
                ('current_fiscal_day', models.IntegerField(blank=True, null=True)),
                ('previous_hash', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants_tenant',
                'indexes': [models.Index(fields=['slug'], name='tenants_ten_slug_63daca_idx'), models.Index(fields=['is_active'], name='tenants_ten_is_acti_8f654a_idx'), models.Index(fields=['device_id'], name='tenants_ten_device__235a6a_idx')],
            },
        ),
    ]
