# Generated by Django 5.2.10 on 2026-03-09 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users who may access this tenant. Superusers can access all tenants.', related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
