# Generated by Django 5.2.10 on 2026-03-09 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_m2m_to_usertenant(apps, schema_editor):
    """Copy existing (user, tenant) from Tenant.users M2M into UserTenant before we switch to through."""
    Tenant = apps.get_model("tenants", "Tenant")
    UserTenant = apps.get_model("tenants", "UserTenant")
    Through = Tenant.users.through
    for row in Through.objects.all():
        UserTenant.objects.get_or_create(
            tenant_id=row.tenant_id,
            user_id=row.user_id,
            defaults={"role": "user"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_user_creation_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='user', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tenant_memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User–tenant membership',
                'verbose_name_plural': 'User–tenant memberships',
                'db_table': 'tenants_usertenant',
            },
        ),
        migrations.RunPython(copy_m2m_to_usertenant, migrations.RunPython.noop),
        migrations.RemoveField(model_name="tenant", name="users"),
        migrations.AddField(
            model_name="tenant",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who may access this tenant (managed via User–tenant memberships). Superusers can access all.",
                related_name="tenants",
                through="tenants.UserTenant",
                through_fields=("tenant", "user"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name='usertenant',
            constraint=models.UniqueConstraint(fields=('user', 'tenant'), name='tenants_usertenant_user_tenant_uniq'),
        ),
    ]
