# Generated by Django 5.2.10 on 2026-02-14 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fiscal", "0013_add_fiscal_edit_attempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineBatchFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_path", models.CharField(max_length=512)),
                ("file_checksum", models.CharField(blank=True, max_length=64)),
                ("receipt_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_batch_files",
                        to="fiscal.fiscaldevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Batch File",
                "verbose_name_plural": "Offline Batch Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflineReceiptQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SUBMITTING", "Submitting"),
                            ("SUBMITTED", "Submitted"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receipt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_queue_entry",
                        to="fiscal.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Receipt Queue",
                "verbose_name_plural": "Offline Receipt Queue",
                "ordering": [
                    "receipt__receipt_global_no",
                    "receipt__fiscal_day_no",
                    "created_at",
                ],
            },
        ),
        migrations.CreateModel(
            name="SubmissionAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("response_status_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("attempt_at", models.DateTimeField(auto_now_add=True)),
                (
                    "queue_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_attempts",
                        to="offline.offlinereceiptqueue",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_attempts",
                        to="fiscal.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Attempt",
                "verbose_name_plural": "Submission Attempts",
                "ordering": ["-attempt_at"],
            },
        ),
    ]
