"""
Django settings for fdms_project project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root when present (no extra dependency)
_env_file = BASE_DIR / ".env"
if _env_file.exists():
    with open(_env_file, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                os.environ.setdefault(key.strip(), value.strip())

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production use fdms_project.settings_production and set SECRET_KEY in env.
# For local dev only: if DJANGO_SECRET_KEY is unset and DEBUG is true, use a dev placeholder.
_DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY and _DEBUG:
    SECRET_KEY = "django-insecure-dev-only-do-not-use-in-production"
DEBUG = _DEBUG

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "www.resumeweaver.co.zw,127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    "daphne",
    "rest_framework",
    "rest_framework_simplejwt",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "django_celery_beat",
    "tenants",
    "dashboard",
    "device_identity",
    "fiscal",
    "invoices",
    "offline",
    "legal",
    "quickbooks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "fdms_project.jwt_middleware.JWTAuthenticationMiddleware",
    "tenants.middleware.TenantResolutionMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "tenants.middleware.TenantResolutionMiddleware",
]

ROOT_URLCONF = "fdms_project.urls"

# FiscalFlow branding (exposed to templates via context processor)
SYSTEM_NAME = "FiscalFlow"
SYSTEM_TAGLINE = "Seamless ZIMRA Fiscal Integration"

# Custom login: use /login/ instead of admin; redirect to dashboard after login
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/login/"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "fdms_project.context_processors.branding",
                "dashboard.context_processors.dashboard_nav",
                "fiscal.context_processors.fdms_device",
                "legal.context_processors.eula_banner",
            ],
        },
    },
]

WSGI_APPLICATION = "fdms_project.wsgi.application"
ASGI_APPLICATION = "fdms_project.asgi.application"

# Celery
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/0")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_ALWAYS_EAGER = os.environ.get("CELERY_TASK_ALWAYS_EAGER", "false").lower() == "true"
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"
# Optional: in-code fallback if no DB schedule exists (django-celery-beat uses DB)
CELERY_BEAT_SCHEDULE = {}

# Channels (WebSocket) - use InMemoryChannelLayer when Redis not configured
_REDIS_URL = os.environ.get("REDIS_URL", "redis://localhost:6379/0")
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [_REDIS_URL]},
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Set DATABASE_URL (e.g. postgres://user:pass@localhost:5432/dbname) to use PostgreSQL.

_db_url = os.environ.get("DATABASE_URL")
if _db_url and "postgres" in _db_url.lower():
    try:
        import dj_database_url
        DATABASES = {"default": dj_database_url.config(conn_max_age=600)}
    except ImportError:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": BASE_DIR / "db.sqlite3",
            }
        }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.environ.get("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles"))
MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media"))
MEDIA_URL = os.environ.get("DJANGO_MEDIA_URL", "/media/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# JWT (REST Framework + Simple JWT)
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
}

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

# FDMS Integration Settings (use env in production)
# Production API base: https://fdmsapi.zimra.co.zw (Swagger: https://fdmsapi.zimra.co.zw/swagger/index.html)
# Test API base: https://fdmsapitest.zimra.co.zw
FDMS_ENV = os.environ.get("FDMS_ENV", "TEST")
_FDMS_BASE_URL = os.environ.get("FDMS_BASE_URL")
if _FDMS_BASE_URL:
    FDMS_BASE_URL = _FDMS_BASE_URL
else:
    FDMS_BASE_URL = "https://fdmsapitest.zimra.co.zw"  # Test default

if DEBUG and FDMS_ENV == "PROD":
    import warnings
    warnings.warn("DEBUG=True with FDMS_ENV=PROD. Block production API in development!", UserWarning)
# FDMS device: use env only; no default secrets in repo. Production uses settings_production.
FDMS_DEVICE_ID = int(os.environ.get("FDMS_DEVICE_ID", "0") or "0")
FDMS_DEVICE_SERIAL_NO = os.environ.get("FDMS_DEVICE_SERIAL_NO", "")
FDMS_ACTIVATION_KEY = os.environ.get("FDMS_ACTIVATION_KEY", "")
FDMS_DEVICE_MODEL_NAME = os.environ.get("FDMS_DEVICE_MODEL_NAME", "Server")
FDMS_DEVICE_MODEL_VERSION = os.environ.get("FDMS_DEVICE_MODEL_VERSION", "v1")

# QuickBooks Integration: use env only; no default client secrets in repo.
QB_CLIENT_ID = os.environ.get("QB_CLIENT_ID", "")
QB_CLIENT_SECRET = os.environ.get("QB_CLIENT_SECRET", "")
QB_REDIRECT_URI = os.environ.get("QB_REDIRECT_URI", "")
# Webhook signature verification (HMAC SHA256). Required for /qb/webhook/ and /api/qb/webhook/
QB_WEBHOOK_VERIFIER = os.environ.get("QB_WEBHOOK_VERIFIER", "")

# QuickBooks OAuth2 (quickbooks app) - use env only.
QUICKBOOKS_CLIENT_ID = os.environ.get("QUICKBOOKS_CLIENT_ID", "")
QUICKBOOKS_CLIENT_SECRET = os.environ.get("QUICKBOOKS_CLIENT_SECRET", "")
QUICKBOOKS_REDIRECT_URI = os.environ.get(
    "QUICKBOOKS_REDIRECT_URI", "https://takatel.tech/qb/callback/"
)
QUICKBOOKS_ENVIRONMENT = os.environ.get("QUICKBOOKS_ENVIRONMENT", "production").lower()
# Base API URLs (no trailing slash)
if QUICKBOOKS_ENVIRONMENT == "sandbox":
    QUICKBOOKS_API_BASE_URL = "https://sandbox-quickbooks.api.intuit.com"
else:
    QUICKBOOKS_API_BASE_URL = "https://quickbooks.api.intuit.com"
# OAuth2 endpoints (same for prod/sandbox)
QUICKBOOKS_OAUTH_AUTHORIZE_URL = "https://appcenter.intuit.com/connect/oauth2"
QUICKBOOKS_OAUTH_TOKEN_URL = "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer"
QUICKBOOKS_OAUTH_REVOKE_URL = "https://oauth.platform.intuit.com/oauth2/v1/tokens/revoke"

# ZIMRA verification portal: QR code URL and URL printed on invoices (production: https://fdms.zimra.co.zw)
ZIMRA_QR_URL = os.environ.get("ZIMRA_QR_URL", "https://fdms.zimra.co.zw")

# PDF persistence mode:
# False (default) => on-demand generation only; do not persist Receipt.pdf_file on submit.
# True => keep legacy behavior and save generated PDF file to media/fiscal_invoices/.
FDMS_PERSIST_PDF = os.environ.get("FDMS_PERSIST_PDF", "false").lower() in ("1", "true", "yes")

# Logging Configuration (LOGS_DIR from env: relative path under BASE_DIR, or absolute)
_logs_dir = os.environ.get("LOGS_DIR", "logs")
LOGS_DIR = Path(_logs_dir) if Path(_logs_dir).is_absolute() else BASE_DIR / _logs_dir
LOGS_DIR.mkdir(parents=True, exist_ok=True)
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
        "json": {
            "()": "fiscal.logging_formatter.JSONFormatter",
            "datefmt": "%Y-%m-%dT%H:%M:%S",
        },
    },
    "handlers": {
        "fdms_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "fdms.log",
            "formatter": "simple",
        },
        "fdms_json_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "fdms_json.log",
            "formatter": "json",
        },
        "fdms_error_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "fdms_error.log",
            "formatter": "simple",
        },
        "fdms_error_json_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": LOGS_DIR / "fdms_error_json.log",
            "formatter": "json",
        },
    },
    "loggers": {
        "fiscal": {
            "handlers": ["fdms_file", "fdms_json_file", "fdms_error_file", "fdms_error_json_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Admin error emails (when DEBUG=False): set DJANGO_ADMIN_EMAIL and SMTP vars in .env
_admin_email = os.environ.get("DJANGO_ADMIN_EMAIL", "").strip()
ADMINS = [("FDMS Admin", _admin_email)] if _admin_email else []
SERVER_EMAIL = os.environ.get("DJANGO_SERVER_EMAIL", _admin_email or "noreply@localhost")

_email_host = os.environ.get("EMAIL_HOST", "").strip()
if _email_host:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = _email_host
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() in ("1", "true", "yes")
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Production / DigitalOcean
SECURE_SSL_REDIRECT = os.environ.get("DJANGO_SECURE_SSL_REDIRECT", "false").lower() in ("1", "true", "yes")
SESSION_COOKIE_SECURE = SECURE_SSL_REDIRECT
CSRF_COOKIE_SECURE = SECURE_SSL_REDIRECT
# Tenant key paths: store outside project directory (e.g. /var/secrets/tenants/<slug>/private.pem)
# Set TENANT_KEYS_BASE_PATH in production; Tenant.private_key_path is relative or absolute.
TENANT_KEYS_BASE_PATH = os.environ.get("TENANT_KEYS_BASE_PATH", "")
# If True, honor X-Tenant-Slug header when X-Internal-Client is present (for internal API clients).
# Normal web users always use session only; superusers always honor the header.
TENANT_HEADER_FOR_INTERNAL_API = os.environ.get("TENANT_HEADER_FOR_INTERNAL_API", "false").lower() in ("1", "true", "yes")
