# Generated by Django 5.2.10 on 2026-02-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FDMSApiLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("request_payload", models.JSONField(default=dict)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "FDMS API Log",
                "verbose_name_plural": "FDMS API Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FiscalDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.IntegerField(unique=True)),
                ("certificate_pem", models.TextField()),
                ("private_key_pem", models.TextField()),
                ("certificate_valid_till", models.DateTimeField(blank=True, null=True)),
                ("is_registered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fiscal Device",
                "verbose_name_plural": "Fiscal Devices",
            },
        ),
        migrations.CreateModel(
            name="FiscalDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_day_no", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
                ("opened_at", models.DateTimeField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fiscal_days",
                        to="fiscal.fiscaldevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Day",
                "verbose_name_plural": "Fiscal Days",
                "unique_together": {("device", "fiscal_day_no")},
            },
        ),
    ]
