# Generated by Django 5.2.10 on 2026-02-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscaldevice",
            name="fiscal_day_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="fiscaldevice",
            name="last_fiscal_day_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fiscaldevice",
            name="last_receipt_global_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
