# Generated by Django 5.2.10 on 2026-02-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0002_fiscaldevice_fiscal_day_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscaldevice",
            name="device_serial_no",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
