# Generated by Django 6.0.2 on 2026-02-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0003_add_device_serial_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscalday",
            name="closing_error_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
