# Generated by Django 6.0.2 on 2026-02-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0004_fiscalday_closing_error_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiscaldevice",
            name="device_model_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="fiscaldevice",
            name="device_model_version",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
