# Generated by Django 6.0.2 on 2026-02-11 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0005_fiscaldevice_device_model_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_day_no", models.IntegerField()),
                ("receipt_global_no", models.IntegerField()),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("receipt_taxes", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="fiscal.fiscaldevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receipt",
                "verbose_name_plural": "Receipts",
                "unique_together": {("device", "receipt_global_no")},
            },
        ),
    ]
