# Generated by Django 6.0.2 on 2026-02-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0006_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="canonical_string",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="fdms_receipt_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="invoice_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_counter",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_hash",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_lines",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_lines_tax_inclusive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_payments",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_server_signature",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_signature_hash",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_signature_sig",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="receipt_type",
            field=models.CharField(default="FiscalInvoice", max_length=20),
        ),
    ]
