# Generated by Django 5.2.10 on 2026-02-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0007_extend_receipt_for_submit"),
    ]

    operations = [
        migrations.AddField(
            model_name="fdmsapilog",
            name="operation_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
