# Generated by Django 5.2.10 on 2026-02-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0008_add_operation_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="original_invoice_no",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="receipt",
            name="original_receipt_global_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
