# Generated by Django 5.2.10 on 2026-02-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0009_add_credit_note_original_refs"),
    ]

    operations = [
        migrations.CreateModel(
            name="FDMSConfigs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.IntegerField(db_index=True)),
                ("raw_response", models.JSONField(default=dict)),
                ("tax_table", models.JSONField(default=list)),
                ("allowed_currencies", models.JSONField(default=list)),
                ("fetched_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "FDMS Configs",
                "verbose_name_plural": "FDMS Configs",
                "ordering": ["-fetched_at"],
            },
        ),
    ]
