# Generated by Django 5.2.10 on 2026-02-13 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0010_add_fdms_configs"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNoteImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_excel_file",
                    models.FileField(
                        blank=True, null=True, upload_to="credit_note_imports/%Y/%m/"
                    ),
                ),
                ("parsed_lines", models.JSONField(default=list)),
                ("original_invoice_snapshot", models.JSONField(default=dict)),
                (
                    "remaining_balance_before",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("credit_total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("credit_reason", models.TextField(blank=True)),
                ("user_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credit_note_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_from_import",
                        to="fiscal.receipt",
                    ),
                ),
                (
                    "original_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_note_imports",
                        to="fiscal.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Note Import",
                "verbose_name_plural": "Credit Note Imports",
                "ordering": ["-created_at"],
            },
        ),
    ]
