# Generated by Django 5.2.10 on 2026-02-13 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0011_add_credit_note_import"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_excel_file",
                    models.FileField(
                        blank=True, null=True, upload_to="invoice_imports/%Y/%m/"
                    ),
                ),
                ("sheet_name", models.CharField(blank=True, max_length=100)),
                ("header_row", models.IntegerField(blank=True, null=True)),
                ("parsed_lines", models.JSONField(default=list)),
                (
                    "receipt_type",
                    models.CharField(default="FiscalInvoice", max_length=20),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("tax_id", models.IntegerField(blank=True, null=True)),
                ("user_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fiscal_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_from_invoice_import",
                        to="fiscal.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Import",
                "verbose_name_plural": "Invoice Imports",
                "ordering": ["-created_at"],
            },
        ),
    ]
