# Generated by Django 5.2.10 on 2026-02-14 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0012_add_invoice_import"),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalEditAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_snapshot", models.JSONField(default=dict)),
                ("attempted_change", models.JSONField(default=dict)),
                ("source", models.CharField(default="QB", max_length=50)),
                ("actor", models.CharField(blank=True, max_length=255)),
                ("blocked", models.BooleanField(default=True)),
                ("diff_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edit_attempts",
                        to="fiscal.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiscal Edit Attempt",
                "verbose_name_plural": "Fiscal Edit Attempts",
                "ordering": ["-created_at"],
            },
        ),
    ]
