# Generated by Django 5.2.10 on 2026-02-14 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0013_add_fiscal_edit_attempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickBooksEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "QuickBooks Event",
                "verbose_name_plural": "QuickBooks Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuickBooksInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qb_invoice_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("qb_customer_id", models.CharField(blank=True, max_length=100)),
                ("currency", models.CharField(default="USD", max_length=10)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("raw_payload", models.JSONField(default=dict)),
                ("fiscalised", models.BooleanField(default=False)),
                ("fiscal_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fiscal_receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qb_invoices",
                        to="fiscal.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "QuickBooks Invoice",
                "verbose_name_plural": "QuickBooks Invoices",
                "ordering": ["-created_at"],
            },
        ),
    ]
