# Generated by Django 5.2.10 on 2026-02-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0014_add_qb_integration"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickBooksConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "realm_id",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("access_token_encrypted", models.TextField(blank=True)),
                ("refresh_token_encrypted", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "QuickBooks Connection",
                "verbose_name_plural": "QuickBooks Connections",
                "ordering": ["-updated_at"],
            },
        ),
    ]
