# Generated by Django 5.2.10 on 2026-02-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0020_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "local_code",
                    models.CharField(
                        help_text="Code used in products, e.g. VAT", max_length=20
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Label for UI, e.g. VAT 15%",
                        max_length=100,
                    ),
                ),
                (
                    "fdms_tax_id",
                    models.IntegerField(
                        help_text="taxID from FDMS GetConfig applicableTaxes"
                    ),
                ),
                (
                    "fdms_tax_code",
                    models.CharField(
                        blank=True,
                        help_text="FDMS taxCode (max 3 chars, e.g. 517). Leave blank to use from GetConfig.",
                        max_length=3,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tax Mapping",
                "verbose_name_plural": "Tax Mappings",
                "ordering": ["sort_order", "local_code"],
                "unique_together": {("local_code",)},
            },
        ),
    ]
