# Generated by Django 5.2.10 on 2026-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0023_add_taxpayer_vat_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxmapping",
            name="tax_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tax percentage from GetConfig (e.g. 15.00). Used when GetConfig unavailable.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
