# Generated by Django 5.2.10 on 2026-02-15 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0024_add_tax_mapping_tax_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("INVOICE", "Invoice"),
                    ("CREDIT_NOTE", "Credit Note"),
                    ("DEBIT_NOTE", "Debit Note"),
                ],
                db_index=True,
                default="INVOICE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="original_invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustments",
                to="fiscal.receipt",
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("document_type", models.CharField(db_index=True, max_length=20)),
                ("last_number", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Document Sequence",
                "verbose_name_plural": "Document Sequences",
                "unique_together": {("year", "document_type")},
            },
        ),
    ]
