# Generated by Django 5.2.10

from decimal import Decimal
from django.db import migrations, models


def set_original_total(apps, schema_editor):
    Receipt = apps.get_model("fiscal", "Receipt")
    from django.db.models import Q
    invoices = Receipt.objects.filter(
        Q(document_type="INVOICE") | Q(document_type="") | Q(document_type__isnull=True)
    ).exclude(
        Q(receipt_type="CreditNote") | Q(receipt_type="CREDITNOTE") | Q(receipt_type="DebitNote") | Q(receipt_type="DEBITNOTE")
    ).exclude(receipt_total__isnull=True)
    for r in invoices:
        r.original_total = r.receipt_total
        r.save(update_fields=["original_total"])


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0027_receipt_credit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="original_total",
            field=models.DecimalField(
                max_digits=14,
                decimal_places=2,
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="total_debited",
            field=models.DecimalField(
                max_digits=14,
                decimal_places=2,
                default=Decimal("0"),
            ),
        ),
        migrations.RunPython(set_original_total, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="receipt",
            name="credit_status",
            field=models.CharField(
                choices=[
                    ("ISSUED", "Issued"),
                    ("PARTIALLY_CREDITED", "Partially Credited"),
                    ("FULLY_CREDITED", "Fully Credited"),
                    ("ADJUSTED_UP", "Adjusted Up"),
                ],
                db_index=True,
                default="ISSUED",
                max_length=30,
            ),
        ),
    ]
