# Generated by Django 6.0.2 on 2026-02-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0030_receipt_qb_id_fiscal_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('receipt_global_no', models.IntegerField(unique=True)),
                ('receipt_date', models.DateField()),
                ('original_invoice_no', models.IntegerField()),
                ('original_invoice_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('credit_reason', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receipt_device_signature_hex', models.TextField()),
                ('qr_code_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('receipt_global_no', models.IntegerField(unique=True)),
                ('receipt_date', models.DateField()),
                ('original_invoice_no', models.IntegerField()),
                ('original_invoice_date', models.DateField()),
                ('currency', models.CharField(max_length=3)),
                ('debit_reason', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('receipt_device_signature_hex', models.TextField()),
                ('qr_code_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Debit Note',
                'verbose_name_plural': 'Debit Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
