# Generated by Django 5.2.10 on 2026-02-24 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0031_creditnote_debitnote'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentsequence',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='taxmapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activityevent_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditevent_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='company',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditnote_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debitnote_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='documentsequence',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentsequence_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fdmsapilog',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fdmsapilog_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fdmsconfigs',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fdmsconfigs_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fiscalday',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscalday_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='fiscaldevice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscaldevice_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='invoicesequence',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoicesequence_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='receiptsubmissionresponse',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiptsubmissionresponse_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='taxmapping',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taxmapping_records', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='receipt_global_no',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='receipt_global_no',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='invoicesequence',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='creditnote',
            unique_together={('tenant', 'receipt_global_no')},
        ),
        migrations.AlterUniqueTogether(
            name='debitnote',
            unique_together={('tenant', 'receipt_global_no')},
        ),
        migrations.AlterUniqueTogether(
            name='documentsequence',
            unique_together={('tenant', 'year', 'document_type')},
        ),
        migrations.AlterUniqueTogether(
            name='invoicesequence',
            unique_together={('tenant', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='taxmapping',
            unique_together={('tenant', 'local_code')},
        ),
        migrations.AddIndex(
            model_name='fdmsapilog',
            index=models.Index(fields=['tenant', 'created_at'], name='fiscal_fdms_tenant__2b5ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalday',
            index=models.Index(fields=['tenant', 'fiscal_day_no'], name='fiscal_fisc_tenant__8c5387_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['tenant', 'created_at'], name='fiscal_rece_tenant__3d65c8_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['tenant', 'fiscal_day_no'], name='fiscal_rece_tenant__edcad4_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['tenant', 'receipt_global_no'], name='fiscal_rece_tenant__66971c_idx'),
        ),
    ]
