# Generated by Django 5.2.10 on 2026-02-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0033_add_fdms_ping_beat_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_code',
            field=models.CharField(default='VAT', max_length=50),
        ),
    ]
