# Generated by Django 5.2.10 on 2026-03-10 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0039_fiscaldevice_tenant_required'),
        ('tenants', '0004_usertenant_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksconnection',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_connection', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='quickbooksinvoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qb_invoices', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='quickbooksconnection',
            name='realm_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quickbooksinvoice',
            name='qb_invoice_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='ZIMRA-compliant InvoiceA4 PDF (Section 10/11/13). Path: media/fiscal_invoices/{receipt_id}.pdf', null=True, upload_to='fiscal_invoices/'),
        ),
        migrations.AddConstraint(
            model_name='quickbooksinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'qb_invoice_id'), name='fiscal_qbinvoice_tenant_qb_id_uniq'),
        ),
    ]
