# Generated by Django 5.2.10 on 2026-03-01 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, max_length=64)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_type', models.CharField(default='Bearer', max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QuickBooks Token',
                'verbose_name_plural': 'QuickBooks Tokens',
                'db_table': 'quickbooks_quickbookstoken',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['realm_id', 'is_active'], name='quickbooks__realm_i_302a2f_idx')],
            },
        ),
    ]
