# Generated by Django 5.2.10 on 2026-03-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0001_initial_quickbooks_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksAPILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, max_length=64)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('intuit_tid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('qb_invoice_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QuickBooks API Log',
                'verbose_name_plural': 'QuickBooks API Logs',
                'db_table': 'quickbooks_quickbooksapilog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['realm_id', 'created_at'], name='quickbooks__realm_i_d62f66_idx'), models.Index(fields=['intuit_tid'], name='quickbooks__intuit__56d967_idx')],
            },
        ),
    ]
