# Generated by Django 5.2.10 on 2026-03-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickbooks', '0002_add_quickbooks_api_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('entity_name', models.CharField(max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'QuickBooks Webhook Event',
                'verbose_name_plural': 'QuickBooks Webhook Events',
                'db_table': 'quickbooks_quickbookswebhookevent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['realm_id', 'entity_id', 'processed'], name='quickbooks__realm_i_2f05ae_idx')],
            },
        ),
    ]
